export type DietaryTag =
  | "veggie"
  | "vegan"
  | "gluten-free"
  | "fish"
  | "chicken"
  | "meat";

export type MealType =
  | "pasta"
  | "rice-bowl"
  | "grain-bowl"
  | "traybake"
  | "soup"
  | "salad"
  | "beans"
  | "quick-pan"
  | "one-pot"
  | "sweet"
  | "breakfast"
  | "snack";

export type Difficulty = "easy" | "medium";

export type RecipeProduct = {
  name: string;
  price: number;
  image: string;
};

export type Recipe = {
  slug: string;
  title: string;
  image: string;
  alt: string;
  intro: string;
  body: string;
  pantryLabel: string;
  product: RecipeProduct;
  companionItems: RecipeProduct[];
  shopAnchor: string;
  shopLabel: string;
  category: "savoury" | "sweet";
  time: string;
  tags: string[];

  dietary: DietaryTag[];
  mealType: MealType;
  difficulty: Difficulty;
  cookingMinutes: number;

  protein: string[];
  mainIngredients: string[];
  pantryMatches: string[];
  flavourProfile: string[];

  isQuick: boolean;
};

export const recipes: Recipe[] = [
  {
    slug: "bucatini-courgette-pesto",
    title: "Bucatini with Charred Courgette & Green Pesto",
    image: "/images/recipes/bucatini-courgette-pesto.jpg",
    alt: "Bucatini with Charred Courgette & Green Pesto",
    intro:
      "A quick green pasta with smoky courgette, glossy pesto and a fresh lemon finish.",
    body: "Cook the bucatini until properly al dente, saving a mug of pasta water before draining. Char the courgette hard in a hot pan so the edges catch and the middle softens. Loosen the pesto with a splash of pasta water, then toss through the bucatini and courgette until glossy. Finish with lemon zest, black pepper and parmesan.",
    pantryLabel: "Made with Bucatini",
    product: {
      name: "Bucatini",
      price: 4.95,
      image: "/images/cupboard/bucatini.jpg",
    },
    companionItems: [
      {
        name: "Sorrel & Walnut Pesto",
        price: 4.5,
        image: "/sorrel-walnut-pesto.png",
      },
    ],
    shopAnchor: "/shop#pantry-additions",
    shopLabel: "Shop pantry range",
    category: "savoury",
    time: "25 mins",
    tags: ["pasta", "quick", "family-friendly"],

    dietary: ["veggie"],
    mealType: "pasta",
    difficulty: "easy",
    cookingMinutes: 25,
    protein: ["bucatini"],
    mainIngredients: [
      "Bucatini",
      "Courgette",
      "Green pesto",
      "Lemon",
      "Parmesan",
    ],
    pantryMatches: ["Bucatini", "Sorrel & Walnut Pesto"],
    flavourProfile: ["lemon"],
    isQuick: true,
  },
  {
    slug: "harissa-butterbeans-peppers-couscous",
    title: "Rose Harissa Butter Beans with Roast Peppers & Giant Couscous",
    image: "/images/recipes/harissa-butterbeans-peppers-couscous.jpg",
    alt: "Rose Harissa Butter Beans with Roast Peppers & Giant Couscous",
    intro:
      "Soft butter beans, sweet roasted peppers and giant couscous in a warm harissa dressing.",
    body: "Cook the giant couscous until tender, then dress it with olive oil and lemon while warm. Warm the butter beans with rose harissa, a splash of water and the roasted peppers until the sauce turns glossy. Fold the couscous through the beans so it catches the harissa dressing. Finish with parsley, yoghurt and a little extra lemon.",
    pantryLabel: "Made with Butter Beans",
    product: {
      name: "Butter Beans",
      price: 3.95,
      image: "/images/cupboard/butter-beans.jpg",
    },
    companionItems: [
      {
        name: "Giant Couscous",
        price: 4.75,
        image: "/images/cupboard/giant-couscous.jpg",
      },
      {
        name: "Rose Harissa",
        price: 5.25,
        image: "/rose-harissa.png",
      },
    ],
    shopAnchor: "/shop#pantry-additions",
    shopLabel: "Shop pantry range",
    category: "savoury",
    time: "40 mins",
    tags: ["grain-bowl", "family-friendly"],

    dietary: ["veggie"],
    mealType: "grain-bowl",
    difficulty: "easy",
    cookingMinutes: 40,
    protein: ["butter beans"],
    mainIngredients: [
      "Butter beans",
      "Roast peppers",
      "Giant couscous",
      "Rose harissa",
      "Parsley",
    ],
    pantryMatches: ["Butter Beans", "Giant Couscous", "Rose Harissa"],
    flavourProfile: ["harissa"],
    isQuick: false,
  },
  {
    slug: "miso-mushroom-farro-greens",
    title: "Miso Mushrooms with Farro & Greens",
    image: "/images/recipes/miso-mushroom-farro.jpg",
    alt: "Miso Mushrooms with Farro & Greens",
    intro:
      "Deeply savoury mushrooms with chewy farro, leafy greens and a miso glaze.",
    body: "Cook the farro until chewy but tender, then drain well. Fry the mushrooms in a hot pan until deeply browned and concentrated. Stir in garlic, white miso and a splash of water to make a savoury glaze. Fold through the greens until just wilted, then spoon over the farro.",
    pantryLabel: "Made with Farro",
    product: {
      name: "Farro",
      price: 4.95,
      image: "/images/cupboard/farro.jpg",
    },
    companionItems: [
      {
        name: "White Miso",
        price: 4.75,
        image: "/white-miso.png",
      },
    ],
    shopAnchor: "/shop#pantry-additions",
    shopLabel: "Shop pantry range",
    category: "savoury",
    time: "35 mins",
    tags: ["grain-bowl"],

    dietary: ["vegan", "veggie", "gluten-free"],
    mealType: "grain-bowl",
    difficulty: "easy",
    cookingMinutes: 35,
    protein: ["mushrooms"],
    mainIngredients: ["Mushrooms", "Farro", "Greens", "White miso", "Garlic"],
    pantryMatches: ["Farro", "White Miso"],
    flavourProfile: ["miso"],
    isQuick: false,
  },
  {
    slug: "tomato-chickpea-orzo-herbs",
    title: "Tomato Chickpea Orzo with Herbs",
    image: "/images/recipes/tomato-chickpea-orzo.jpg",
    alt: "Tomato Chickpea Orzo with Herbs",
    intro:
      "A one-pan orzo with chickpeas, tomatoes and soft herbs for an easy midweek supper.",
    body: "Soften garlic in olive oil until fragrant but not browned. Add tomatoes, chickpeas and orzo with enough water or stock to cook gently. Simmer until the orzo is tender and the sauce looks glossy rather than wet. Finish with basil, black pepper and a final drizzle of olive oil.",
    pantryLabel: "Made with Orzo",
    product: {
      name: "Orzo",
      price: 4.75,
      image: "/images/cupboard/orzo.jpg",
    },
    companionItems: [
      {
        name: "Chickpeas",
        price: 3.75,
        image: "/images/cupboard/chickpeas.jpg",
      },
      {
        name: "Premium Whole Tomatoes",
        price: 3.95,
        image: "/images/cupboard/whole-tomatoes.jpg",
      },
    ],
    shopAnchor: "/shop#pantry-additions",
    shopLabel: "Shop pantry range",
    category: "savoury",
    time: "25 mins",
    tags: ["quick-pan", "quick", "family-friendly"],

    dietary: ["vegan", "veggie"],
    mealType: "quick-pan",
    difficulty: "easy",
    cookingMinutes: 25,
    protein: ["chickpeas"],
    mainIngredients: ["Orzo", "Chickpeas", "Tomatoes", "Garlic", "Basil"],
    pantryMatches: ["Orzo", "Chickpeas", "Premium Whole Tomatoes"],
    flavourProfile: ["tomatoey"],
    isQuick: true,
  },
  {
    slug: "gochujang-broccoli-rice-bowls",
    title: "Gochujang Broccoli Rice Bowls",
    image: "/images/recipes/gochujang-broccoli-rice-bowl.jpg",
    alt: "Gochujang Broccoli Rice Bowls",
    intro:
      "Charred broccoli with sticky gochujang dressing, rice and a cooling crunchy finish.",
    body: "Cook the rice until fluffy and season lightly while warm. Char the broccoli in a hot pan or roasting tray until the tips catch. Toss the broccoli with gochujang, lime and a little sweetness until sticky. Serve over rice with cucumber, spring onions and sesame if using.",
    pantryLabel: "Made with Signature Gochujang",
    product: {
      name: "Signature Gochujang",
      price: 5.25,
      image: "/gochujang.png",
    },
    companionItems: [],
    shopAnchor: "/shop#pantry-additions",
    shopLabel: "Shop pantry range",
    category: "savoury",
    time: "25 mins",
    tags: ["rice-bowl", "quick"],

    dietary: ["vegan", "veggie", "gluten-free"],
    mealType: "rice-bowl",
    difficulty: "easy",
    cookingMinutes: 25,
    protein: ["broccoli"],
    mainIngredients: [
      "Broccoli",
      "Rice",
      "Gochujang",
      "Cucumber",
      "Spring onions",
    ],
    pantryMatches: ["Signature Gochujang"],
    flavourProfile: ["balanced", "seasonal", "weeknight"],
    isQuick: true,
  },
  {
    slug: "cauliflower-lentils-polenta",
    title: "Roast Cauliflower Lentils with Soft Polenta",
    image: "/images/recipes/cauliflower-lentil-polenta.jpg",
    alt: "Roast Cauliflower Lentils with Soft Polenta",
    intro:
      "A comforting bowl of roasted cauliflower, puy lentils and creamy polenta.",
    body: "Roast the cauliflower with oil, salt and thyme until golden at the edges. Warm the puy lentils with garlic, olive oil and a splash of stock or water. Cook the polenta slowly until soft, creamy and spoonable. Spoon the lentils and cauliflower over the polenta and finish with pepper.",
    pantryLabel: "Made with Puy Lentils",
    product: {
      name: "Puy Lentils",
      price: 4.95,
      image: "/images/cupboard/puy-lentils.jpg",
    },
    companionItems: [
      {
        name: "Polenta",
        price: 4.25,
        image: "/images/cupboard/polenta.jpg",
      },
    ],
    shopAnchor: "/shop#pantry-additions",
    shopLabel: "Shop pantry range",
    category: "savoury",
    time: "40 mins",
    tags: ["quick-pan", "family-friendly"],

    dietary: ["vegan", "veggie", "gluten-free"],
    mealType: "quick-pan",
    difficulty: "easy",
    cookingMinutes: 40,
    protein: ["lentils"],
    mainIngredients: [
      "Cauliflower",
      "Puy lentils",
      "Polenta",
      "Thyme",
      "Garlic",
    ],
    pantryMatches: ["Puy Lentils", "Polenta"],
    flavourProfile: ["balanced", "seasonal", "weeknight"],
    isQuick: false,
  },
  {
    slug: "aubergine-cannellini-tomatoes",
    title: "Aubergine, Cannellini Beans & Tomatoes",
    image: "/images/recipes/aubergine-cannellini-tomatoes.jpg",
    alt: "Aubergine, Cannellini Beans & Tomatoes",
    intro:
      "A soft, tomato-rich pan of aubergine and beans, good with bread, rice or couscous.",
    body: "Cook the aubergine in olive oil until soft, golden and collapsing. Add garlic and tomatoes, then simmer until the sauce thickens. Fold through the cannellini beans and warm gently so they stay whole. Finish with parsley and serve with bread, rice or couscous.",
    pantryLabel: "Made with Cannellini Beans",
    product: {
      name: "Cannellini Beans",
      price: 3.95,
      image: "/images/cupboard/cannellini-beans.jpg",
    },
    companionItems: [
      {
        name: "Premium Whole Tomatoes",
        price: 3.95,
        image: "/images/cupboard/whole-tomatoes.jpg",
      },
    ],
    shopAnchor: "/shop#pantry-additions",
    shopLabel: "Shop pantry range",
    category: "savoury",
    time: "40 mins",
    tags: ["beans"],

    dietary: ["vegan", "veggie", "gluten-free"],
    mealType: "beans",
    difficulty: "easy",
    cookingMinutes: 40,
    protein: ["cannellini beans"],
    mainIngredients: [
      "Aubergine",
      "Cannellini beans",
      "Tomatoes",
      "Garlic",
      "Parsley",
    ],
    pantryMatches: ["Cannellini Beans", "Premium Whole Tomatoes"],
    flavourProfile: ["tomatoey"],
    isQuick: false,
  },
  {
    slug: "beetroot-grain-salad-herbs",
    title: "Beetroot Grain Salad with Herbs",
    image: "/images/recipes/beetroot-grain-salad.jpg",
    alt: "Beetroot Grain Salad with Herbs",
    intro:
      "Earthy beetroot, grains, herbs and a sharp dressing for a useful lunch or light supper.",
    body: "Cook the farro until chewy, then dress it while warm with lemon, oil and salt. Slice the beetroot and toss it through the grains so the colour bleeds slightly. Fold through parsley and walnuts for freshness and crunch. Finish with extra lemon and goat’s cheese if liked.",
    pantryLabel: "Made with Farro",
    product: {
      name: "Farro",
      price: 4.95,
      image: "/images/cupboard/farro.jpg",
    },
    companionItems: [],
    shopAnchor: "/shop#pantry-additions",
    shopLabel: "Shop pantry range",
    category: "savoury",
    time: "35 mins",
    tags: ["grain-bowl"],

    dietary: ["vegan", "veggie", "gluten-free"],
    mealType: "grain-bowl",
    difficulty: "easy",
    cookingMinutes: 35,
    protein: ["walnuts"],
    mainIngredients: ["Beetroot", "Farro", "Parsley", "Lemon", "Walnuts"],
    pantryMatches: ["Farro"],
    flavourProfile: ["lemon"],
    isQuick: false,
  },
  {
    slug: "green-bean-lemon-risotto",
    title: "Green Bean & Lemon Risotto",
    image: "/images/recipes/green-bean-risotto.jpg",
    alt: "Green Bean & Lemon Risotto",
    intro:
      "A gentle risotto with green beans, lemon and herbs for a calm midweek dinner.",
    body: "Soften the base of the risotto gently before stirring in the rice. Add hot stock gradually, stirring until the rice turns creamy. Add the green beans near the end so they stay bright. Finish off the heat with lemon zest, parmesan, mint and black pepper.",
    pantryLabel: "Made with Risotto Rice",
    product: {
      name: "Risotto Rice",
      price: 4.95,
      image: "/images/cupboard/risotto-rice.jpg",
    },
    companionItems: [],
    shopAnchor: "/shop#pantry-additions",
    shopLabel: "Shop pantry range",
    category: "savoury",
    time: "35 mins",
    tags: ["one-pot", "family-friendly"],

    dietary: ["veggie", "gluten-free"],
    mealType: "one-pot",
    difficulty: "easy",
    cookingMinutes: 35,
    protein: ["risotto rice"],
    mainIngredients: [
      "Risotto rice",
      "Green beans",
      "Lemon",
      "Parmesan",
      "Mint",
    ],
    pantryMatches: ["Risotto Rice"],
    flavourProfile: ["lemon"],
    isQuick: false,
  },
  {
    slug: "pepper-potato-herb-frittata",
    title: "Pepper, Potato & Herb Frittata",
    image: "/images/recipes/pepper-potato-frittata.jpg",
    alt: "Pepper, Potato & Herb Frittata",
    intro:
      "A flexible egg-based supper for using up peppers, potatoes and soft herbs.",
    body: "Cook the sliced potatoes until tender and lightly golden. Soften the peppers and onion in the same pan until sweet. Pour in seasoned eggs and cook gently until the edges begin to set. Finish under the grill, then scatter with parsley before serving.",
    pantryLabel: "Weekly planner meal",
    product: {
      name: "Weekly Produce Box",
      price: 20,
      image: "/weekly-harvest-box.png",
    },
    companionItems: [],
    shopAnchor: "/shop#pantry-additions",
    shopLabel: "Shop pantry range",
    category: "savoury",
    time: "25 mins",
    tags: ["quick-pan", "quick", "family-friendly"],

    dietary: ["veggie", "gluten-free"],
    mealType: "quick-pan",
    difficulty: "easy",
    cookingMinutes: 25,
    protein: ["eggs"],
    mainIngredients: ["Eggs", "Peppers", "Potatoes", "Parsley", "Onion"],
    pantryMatches: [],
    flavourProfile: ["balanced", "seasonal", "weeknight"],
    isQuick: true,
  },
  {
    slug: "salmon-dill-crushed-potato-traybake",
    title: "Salmon, Dill & Crushed Potato Traybake",
    image: "/images/recipes/salmon-dill-crushed-potato-traybake.jpg",
    alt: "Salmon, Dill & Crushed Potato Traybake",
    intro:
      "A simple traybake with flaky salmon, crushed potatoes, greens and a bright dill finish.",
    body: "Boil the potatoes until tender, then lightly crush them on a tray. Roast the crushed potatoes until crisp at the edges. Add salmon and green beans for the final stretch so the fish stays soft. Finish with lemon, dill and a spoon of yoghurt if liked.",
    pantryLabel: "Weekly planner meal",
    product: {
      name: "Weekly Produce Box",
      price: 20,
      image: "/weekly-harvest-box.png",
    },
    companionItems: [],
    shopAnchor: "/shop#pantry-additions",
    shopLabel: "Shop pantry range",
    category: "savoury",
    time: "35 mins",
    tags: ["traybake", "family-friendly"],

    dietary: ["fish", "gluten-free"],
    mealType: "traybake",
    difficulty: "easy",
    cookingMinutes: 35,
    protein: ["salmon"],
    mainIngredients: ["Salmon", "Potatoes", "Dill", "Lemon", "Green beans"],
    pantryMatches: [],
    flavourProfile: ["lemon"],
    isQuick: false,
  },
  {
    slug: "gochujang-chicken-rice-cucumber",
    title: "Gochujang Chicken Rice Bowls with Cucumber",
    image: "/images/recipes/gochujang-chicken-rice-cucumber.jpg",
    alt: "Gochujang Chicken Rice Bowls with Cucumber",
    intro:
      "Sticky gochujang chicken with rice, cucumber, herbs and a fresh crunchy finish.",
    body: "Cook the rice until fluffy and keep warm. Pan-fry the chicken until golden and cooked through. Toss the chicken with gochujang, lime and a little sweetness until sticky. Serve with cucumber, spring onions and sesame over the rice.",
    pantryLabel: "Made with Signature Gochujang",
    product: {
      name: "Signature Gochujang",
      price: 5.25,
      image: "/gochujang.png",
    },
    companionItems: [],
    shopAnchor: "/shop#pantry-additions",
    shopLabel: "Shop pantry range",
    category: "savoury",
    time: "25 mins",
    tags: ["rice-bowl", "quick", "family-friendly"],

    dietary: ["chicken", "gluten-free"],
    mealType: "rice-bowl",
    difficulty: "easy",
    cookingMinutes: 25,
    protein: ["chicken"],
    mainIngredients: [
      "Chicken",
      "Rice",
      "Gochujang",
      "Cucumber",
      "Spring onions",
    ],
    pantryMatches: ["Signature Gochujang"],
    flavourProfile: ["balanced", "seasonal", "weeknight"],
    isQuick: true,
  },
  {
    slug: "cashew-broccoli-noodles-lime",
    title: "Cashew Broccoli Noodles with Lime",
    image: "/images/recipes/cashew-broccoli-noodles-lime.jpg",
    alt: "Cashew Broccoli Noodles with Lime",
    intro: "Noodles with charred broccoli, cashew sauce, lime and herbs.",
    body: "Cook the noodles until just tender, then rinse or toss lightly so they do not clump. Char the broccoli until smoky at the edges but still green. Stir cashew butter or blended cashews with lime, soy and warm water into a loose sauce. Toss everything together and finish with coriander and extra lime.",
    pantryLabel: "Weekly planner meal",
    product: {
      name: "Weekly Produce Box",
      price: 20,
      image: "/weekly-harvest-box.png",
    },
    companionItems: [],
    shopAnchor: "/shop#pantry-additions",
    shopLabel: "Shop pantry range",
    category: "savoury",
    time: "25 mins",
    tags: ["quick-pan", "quick"],

    dietary: ["vegan", "veggie"],
    mealType: "quick-pan",
    difficulty: "easy",
    cookingMinutes: 25,
    protein: ["cashews"],
    mainIngredients: [
      "Broccoli",
      "Rice noodles",
      "Cashews",
      "Lime",
      "Coriander",
    ],
    pantryMatches: [],
    flavourProfile: ["balanced", "seasonal", "weeknight"],
    isQuick: true,
  },
  {
    slug: "crispy-tofu-peanut-rice-bowls",
    title: "Crispy Tofu Peanut Rice Bowls",
    image: "/images/recipes/crispy-tofu-peanut-rice-bowls.jpg",
    alt: "Crispy Tofu Peanut Rice Bowls",
    intro: "Crispy tofu, vegetables and rice with a creamy peanut-lime sauce.",
    body: "Press and cube the tofu, then fry until crisp and golden. Cook the rice until fluffy and season lightly. Mix peanut sauce with lime, soy and warm water until spoonable. Serve tofu over rice with cucumber, carrots and plenty of sauce.",
    pantryLabel: "Weekly planner meal",
    product: {
      name: "Weekly Produce Box",
      price: 20,
      image: "/weekly-harvest-box.png",
    },
    companionItems: [],
    shopAnchor: "/shop#pantry-additions",
    shopLabel: "Shop pantry range",
    category: "savoury",
    time: "35 mins",
    tags: ["rice-bowl"],

    dietary: ["vegan", "veggie", "gluten-free"],
    mealType: "rice-bowl",
    difficulty: "easy",
    cookingMinutes: 35,
    protein: ["tofu"],
    mainIngredients: ["Tofu", "Rice", "Peanut sauce", "Cucumber", "Carrots"],
    pantryMatches: [],
    flavourProfile: ["balanced", "seasonal", "weeknight"],
    isQuick: false,
  },
  {
    slug: "roast-pepper-cashew-cream-casarecce",
    title: "Roast Pepper Cashew Cream Casarecce",
    image: "/images/recipes/roast-pepper-cashew-cream-casarecce.jpg",
    alt: "Roast Pepper Cashew Cream Casarecce",
    intro:
      "Casarecce folded through a silky roast pepper and cashew cream sauce.",
    body: "Cook the casarecce until al dente, saving some pasta water. Blend roasted peppers with soaked cashews, garlic and seasoning until silky. Warm the sauce gently and loosen it with pasta water. Toss through the pasta and finish with basil and black pepper.",
    pantryLabel: "Made with Casarecce Pasta",
    product: {
      name: "Casarecce Pasta",
      price: 4.95,
      image: "/images/cupboard/casarecce.jpg",
    },
    companionItems: [],
    shopAnchor: "/shop#pantry-additions",
    shopLabel: "Shop pantry range",
    category: "savoury",
    time: "40 mins",
    tags: ["pasta", "family-friendly"],

    dietary: ["veggie"],
    mealType: "pasta",
    difficulty: "easy",
    cookingMinutes: 40,
    protein: ["cashews"],
    mainIngredients: [
      "Casarecce Pasta",
      "Roast peppers",
      "Cashews",
      "Garlic",
      "Basil",
    ],
    pantryMatches: ["Casarecce Pasta"],
    flavourProfile: ["balanced", "seasonal", "weeknight"],
    isQuick: false,
  },
  {
    slug: "lemon-herb-chicken-giant-couscous",
    title: "Lemon Herb Chicken with Giant Couscous",
    image: "/images/recipes/lemon-herb-chicken-giant-couscous.jpg",
    alt: "Lemon Herb Chicken with Giant Couscous",
    intro: "Golden chicken with herby giant couscous, vegetables and lemon.",
    body: "Cook the giant couscous until tender, then dress with lemon and olive oil. Season the chicken and pan-fry until golden and cooked through. Char the courgette or seasonal vegetables in the same pan. Slice the chicken over the couscous and finish with parsley and lemon.",
    pantryLabel: "Made with Giant Couscous",
    product: {
      name: "Giant Couscous",
      price: 4.75,
      image: "/images/cupboard/giant-couscous.jpg",
    },
    companionItems: [],
    shopAnchor: "/shop#pantry-additions",
    shopLabel: "Shop pantry range",
    category: "savoury",
    time: "35 mins",
    tags: ["grain-bowl", "family-friendly"],

    dietary: ["chicken"],
    mealType: "grain-bowl",
    difficulty: "easy",
    cookingMinutes: 35,
    protein: ["chicken"],
    mainIngredients: [
      "Chicken",
      "Giant couscous",
      "Lemon",
      "Parsley",
      "Courgette",
    ],
    pantryMatches: ["Giant Couscous"],
    flavourProfile: ["lemon"],
    isQuick: false,
  },
  {
    slug: "salmon-crushed-peas-herby-potatoes",
    title: "Salmon with Crushed Peas & Herby Potatoes",
    image: "/images/recipes/salmon-crushed-peas-herby-potatoes.jpg",
    alt: "Salmon with Crushed Peas & Herby Potatoes",
    intro: "A fresh salmon supper with crushed peas, soft herbs and potatoes.",
    body: "Boil the potatoes until tender, then toss with olive oil and herbs. Cook the salmon gently until just flaky. Crush the peas with mint, lemon, salt and a little olive oil. Serve the salmon with herby potatoes and the bright crushed peas.",
    pantryLabel: "Weekly planner meal",
    product: {
      name: "Weekly Produce Box",
      price: 20,
      image: "/weekly-harvest-box.png",
    },
    companionItems: [],
    shopAnchor: "/shop#pantry-additions",
    shopLabel: "Shop pantry range",
    category: "savoury",
    time: "35 mins",
    tags: ["quick-pan", "family-friendly"],

    dietary: ["fish", "gluten-free"],
    mealType: "quick-pan",
    difficulty: "easy",
    cookingMinutes: 35,
    protein: ["salmon"],
    mainIngredients: ["Salmon", "Peas", "Potatoes", "Mint", "Lemon"],
    pantryMatches: [],
    flavourProfile: ["herby", "lemon"],
    isQuick: false,
  },
  {
    slug: "roast-fennel-tomato-burrata-toasts",
    title: "Roast Fennel & Tomato Burrata Toasts",
    image: "/images/recipes/roast-fennel-tomato-burrata-toasts.jpg",
    alt: "Roast Fennel & Tomato Burrata Toasts",
    intro: "Sweet roast fennel and tomatoes over toast with creamy burrata.",
    body: "Roast fennel and tomatoes until soft, sweet and slightly jammy. Toast the sourdough until crisp enough to hold the topping. Pile the roasted vegetables over the toast while still warm. Tear over burrata and finish with basil, olive oil and black pepper.",
    pantryLabel: "Weekly planner meal",
    product: {
      name: "Weekly Produce Box",
      price: 20,
      image: "/weekly-harvest-box.png",
    },
    companionItems: [],
    shopAnchor: "/shop#pantry-additions",
    shopLabel: "Shop pantry range",
    category: "savoury",
    time: "25 mins",
    tags: ["quick-pan", "quick"],

    dietary: ["veggie"],
    mealType: "quick-pan",
    difficulty: "easy",
    cookingMinutes: 25,
    protein: ["fennel"],
    mainIngredients: ["Fennel", "Tomatoes", "Burrata", "Sourdough", "Basil"],
    pantryMatches: [],
    flavourProfile: ["tomatoey"],
    isQuick: true,
  },
  {
    slug: "spinach-ricotta-herb-stuffed-peppers",
    title: "Spinach, Ricotta & Herb Stuffed Peppers",
    image: "/images/recipes/spinach-ricotta-herb-stuffed-peppers.jpg",
    alt: "Spinach, Ricotta & Herb Stuffed Peppers",
    intro: "Sweet peppers filled with spinach, ricotta, herbs and grains.",
    body: "Halve the peppers and roast until beginning to soften. Mix cooked rice with spinach, ricotta, herbs and seasoning. Fill the peppers generously and bake until the tops turn golden. Serve with extra herbs and a simple green salad.",
    pantryLabel: "Weekly planner meal",
    product: {
      name: "Weekly Produce Box",
      price: 20,
      image: "/weekly-harvest-box.png",
    },
    companionItems: [],
    shopAnchor: "/shop#pantry-additions",
    shopLabel: "Shop pantry range",
    category: "savoury",
    time: "40 mins",
    tags: ["one-pot", "family-friendly"],

    dietary: ["veggie", "gluten-free"],
    mealType: "one-pot",
    difficulty: "easy",
    cookingMinutes: 40,
    protein: ["peppers"],
    mainIngredients: ["Peppers", "Spinach", "Ricotta", "Herbs", "Rice"],
    pantryMatches: [],
    flavourProfile: ["balanced", "seasonal", "weeknight"],
    isQuick: false,
  },
  {
    slug: "sticky-soy-chicken-greens-rice",
    title: "Sticky Soy Chicken with Greens & Rice",
    image: "/images/recipes/sticky-soy-chicken-greens-rice.jpg",
    alt: "Sticky Soy Chicken with Greens & Rice",
    intro: "Glossy soy chicken with greens, rice and a sharp fresh finish.",
    body: "Cook the rice until fluffy and keep warm. Pan-fry the chicken until golden on the outside. Add soy, ginger and a little sweetness to make a glossy glaze. Serve with quickly wilted greens and a sharp squeeze of lime.",
    pantryLabel: "Weekly planner meal",
    product: {
      name: "Weekly Produce Box",
      price: 20,
      image: "/weekly-harvest-box.png",
    },
    companionItems: [],
    shopAnchor: "/shop#pantry-additions",
    shopLabel: "Shop pantry range",
    category: "savoury",
    time: "25 mins",
    tags: ["one-pot", "quick", "family-friendly"],

    dietary: ["chicken", "gluten-free"],
    mealType: "one-pot",
    difficulty: "easy",
    cookingMinutes: 25,
    protein: ["chicken"],
    mainIngredients: ["Chicken", "Rice", "Greens", "Soy", "Ginger"],
    pantryMatches: [],
    flavourProfile: ["sticky"],
    isQuick: true,
  },
  {
    slug: "creamy-tuscan-butterbeans-greens",
    title: "Creamy Tuscan Butter Beans with Greens",
    image: "/images/recipes/creamy-tuscan-butterbeans-greens.jpg",
    alt: "Creamy Tuscan Butter Beans with Greens",
    intro:
      "Butter beans in a creamy garlic sauce with greens, herbs and parmesan.",
    body: "Warm garlic gently in olive oil until fragrant. Add butter beans, cream and a splash of water, then simmer until glossy. Fold through the greens until just wilted. Finish with parmesan, herbs and black pepper.",
    pantryLabel: "Made with Butter Beans",
    product: {
      name: "Butter Beans",
      price: 3.95,
      image: "/images/cupboard/butter-beans.jpg",
    },
    companionItems: [],
    shopAnchor: "/shop#pantry-additions",
    shopLabel: "Shop pantry range",
    category: "savoury",
    time: "40 mins",
    tags: ["beans", "family-friendly"],

    dietary: ["veggie", "gluten-free"],
    mealType: "beans",
    difficulty: "easy",
    cookingMinutes: 40,
    protein: ["butter beans"],
    mainIngredients: ["Butter beans", "Greens", "Cream", "Garlic", "Parmesan"],
    pantryMatches: ["Butter Beans"],
    flavourProfile: ["creamy"],
    isQuick: false,
  },
  {
    slug: "charred-courgette-whipped-feta-orzo",
    title: "Charred Courgette & Whipped Feta Orzo",
    image: "/images/recipes/charred-courgette-whipped-feta-orzo.jpg",
    alt: "Charred Courgette & Whipped Feta Orzo",
    intro: "Lemony orzo with charred courgette, herbs and whipped feta.",
    body: "Cook the orzo until tender, then drain and dress with lemon. Char the courgette hard so the edges brown and soften. Whip or mash feta with lemon and olive oil until creamy. Serve the orzo with courgette, mint and spoonfuls of whipped feta.",
    pantryLabel: "Made with Orzo",
    product: {
      name: "Orzo",
      price: 4.75,
      image: "/images/cupboard/orzo.jpg",
    },
    companionItems: [],
    shopAnchor: "/shop#pantry-additions",
    shopLabel: "Shop pantry range",
    category: "savoury",
    time: "35 mins",
    tags: ["quick-pan", "family-friendly"],

    dietary: ["veggie"],
    mealType: "quick-pan",
    difficulty: "easy",
    cookingMinutes: 35,
    protein: ["orzo"],
    mainIngredients: ["Orzo", "Courgette", "Feta", "Lemon", "Mint"],
    pantryMatches: ["Orzo"],
    flavourProfile: ["lemon"],
    isQuick: false,
  },
  {
    slug: "coconut-lime-greens-crispy-tofu",
    title: "Coconut Lime Greens with Crispy Tofu",
    image: "/images/recipes/coconut-lime-greens-crispy-tofu.jpg",
    alt: "Coconut Lime Greens with Crispy Tofu",
    intro: "A coconut-lime greens bowl with crispy tofu and rice.",
    body: "Cook the rice until fluffy. Fry the tofu until crisp and golden on the edges. Simmer the greens briefly with coconut milk, lime and seasoning. Serve the tofu over rice with coconut greens and extra lime.",
    pantryLabel: "Weekly planner meal",
    product: {
      name: "Weekly Produce Box",
      price: 20,
      image: "/weekly-harvest-box.png",
    },
    companionItems: [],
    shopAnchor: "/shop#pantry-additions",
    shopLabel: "Shop pantry range",
    category: "savoury",
    time: "35 mins",
    tags: ["one-pot"],

    dietary: ["vegan", "veggie", "gluten-free"],
    mealType: "one-pot",
    difficulty: "easy",
    cookingMinutes: 35,
    protein: ["tofu"],
    mainIngredients: ["Tofu", "Greens", "Coconut milk", "Lime", "Rice"],
    pantryMatches: [],
    flavourProfile: ["coconut"],
    isQuick: false,
  },
  {
    slug: "roasted-tomato-burrata-gnocchi",
    title: "Roasted Tomato Burrata Gnocchi",
    image: "/images/recipes/roasted-tomato-burrata-gnocchi.jpg",
    alt: "Roasted Tomato Burrata Gnocchi",
    intro: "Crispy gnocchi with roasted tomatoes, basil oil and burrata.",
    body: "Roast tomatoes with garlic, olive oil and salt until they collapse. Pan-fry or bake the gnocchi until golden and crisp-edged. Toss the gnocchi through the roasted tomato juices. Finish with torn burrata, basil and black pepper.",
    pantryLabel: "Weekly planner meal",
    product: {
      name: "Weekly Produce Box",
      price: 20,
      image: "/weekly-harvest-box.png",
    },
    companionItems: [],
    shopAnchor: "/shop#pantry-additions",
    shopLabel: "Shop pantry range",
    category: "savoury",
    time: "40 mins",
    tags: ["pasta", "family-friendly"],

    dietary: ["veggie"],
    mealType: "pasta",
    difficulty: "easy",
    cookingMinutes: 40,
    protein: ["gnocchi"],
    mainIngredients: ["Gnocchi", "Tomatoes", "Burrata", "Basil", "Garlic"],
    pantryMatches: [],
    flavourProfile: ["tomatoey"],
    isQuick: false,
  },
  {
    slug: "hot-honey-halloumi-herby-couscous",
    title: "Hot Honey Halloumi with Herby Couscous",
    image: "/images/recipes/hot-honey-halloumi-couscous.jpg",
    alt: "Hot Honey Halloumi with Herby Couscous",
    intro:
      "Golden halloumi with lemony couscous, herbs and a chilli honey finish.",
    body: "Cook the giant couscous until tender, then dress with lemon and olive oil. Pan-fry the halloumi until deeply golden on both sides. Toss cucumber and mint through the couscous for freshness. Drizzle the halloumi with hot honey and serve over the herby couscous.",
    pantryLabel: "Made with Giant Couscous",
    product: {
      name: "Giant Couscous",
      price: 4.75,
      image: "/images/cupboard/giant-couscous.jpg",
    },
    companionItems: [],
    shopAnchor: "/shop#pantry-additions",
    shopLabel: "Shop pantry range",
    category: "savoury",
    time: "25 mins",
    tags: ["grain-bowl", "quick", "family-friendly"],

    dietary: ["veggie"],
    mealType: "grain-bowl",
    difficulty: "easy",
    cookingMinutes: 25,
    protein: ["halloumi"],
    mainIngredients: [
      "Halloumi",
      "Giant couscous",
      "Cucumber",
      "Mint",
      "Hot honey",
    ],
    pantryMatches: ["Giant Couscous"],
    flavourProfile: ["herby"],
    isQuick: true,
  },
  {
    slug: "smoky-sweet-potato-black-bean-bowls",
    title: "Smoky Sweet Potato Black Bean Bowls",
    image: "/images/recipes/smoky-sweet-potato-black-bean-bowls.jpg",
    alt: "Smoky Sweet Potato Black Bean Bowls",
    intro: "Roasted sweet potato, black beans, rice and avocado yoghurt.",
    body: "Roast sweet potato with smoky spices until soft and caramelised. Warm the black beans with lime, garlic and seasoning. Cook the rice until fluffy. Serve with avocado yoghurt, coriander and extra lime.",
    pantryLabel: "Weekly planner meal",
    product: {
      name: "Weekly Produce Box",
      price: 20,
      image: "/weekly-harvest-box.png",
    },
    companionItems: [],
    shopAnchor: "/shop#pantry-additions",
    shopLabel: "Shop pantry range",
    category: "savoury",
    time: "35 mins",
    tags: ["rice-bowl", "family-friendly"],

    dietary: ["vegan", "veggie", "gluten-free"],
    mealType: "rice-bowl",
    difficulty: "easy",
    cookingMinutes: 35,
    protein: ["sweet potato"],
    mainIngredients: [
      "Sweet potato",
      "Black beans",
      "Rice",
      "Avocado",
      "Coriander",
    ],
    pantryMatches: [],
    flavourProfile: ["balanced", "seasonal", "weeknight"],
    isQuick: false,
  },
  {
    slug: "chicken-leek-mustard-cream-casarecce",
    title: "Chicken, Leek & Mustard Cream Casarecce",
    image: "/images/recipes/chicken-leek-mustard-cream-casarecce.jpg",
    alt: "Chicken, Leek & Mustard Cream Casarecce",
    intro: "A comforting casarecce with chicken, soft leeks and mustard cream.",
    body: "Cook the casarecce until al dente, saving a splash of pasta water. Soften the leeks slowly until sweet and silky. Add cooked chicken, mustard and cream, then loosen with pasta water. Toss through the pasta and finish with black pepper.",
    pantryLabel: "Made with Casarecce Pasta",
    product: {
      name: "Casarecce Pasta",
      price: 4.95,
      image: "/images/cupboard/casarecce.jpg",
    },
    companionItems: [],
    shopAnchor: "/shop#pantry-additions",
    shopLabel: "Shop pantry range",
    category: "savoury",
    time: "40 mins",
    tags: ["pasta", "family-friendly"],

    dietary: ["chicken"],
    mealType: "pasta",
    difficulty: "easy",
    cookingMinutes: 40,
    protein: ["chicken"],
    mainIngredients: [
      "Casarecce Pasta",
      "Chicken",
      "Leeks",
      "Mustard",
      "Cream",
    ],
    pantryMatches: ["Casarecce Pasta"],
    flavourProfile: ["balanced", "seasonal", "weeknight"],
    isQuick: false,
  },
  {
    slug: "roasted-carrot-labneh-toasts-dukkah",
    title: "Roasted Carrot Labneh Toasts with Dukkah",
    image: "/images/recipes/roasted-carrot-labneh-toasts.jpg",
    alt: "Roasted Carrot Labneh Toasts with Dukkah",
    intro: "Roasted carrots over thick labneh on toast with herbs and dukkah.",
    body: "Roast the carrots until tender, browned and sweet at the edges. Toast the sourdough until crisp. Spread thick labneh over the toast. Top with carrots, parsley, dukkah and a drizzle of olive oil.",
    pantryLabel: "Weekly planner meal",
    product: {
      name: "Weekly Produce Box",
      price: 20,
      image: "/weekly-harvest-box.png",
    },
    companionItems: [],
    shopAnchor: "/shop#pantry-additions",
    shopLabel: "Shop pantry range",
    category: "savoury",
    time: "25 mins",
    tags: ["quick-pan", "quick"],

    dietary: ["veggie"],
    mealType: "quick-pan",
    difficulty: "easy",
    cookingMinutes: 25,
    protein: ["carrots"],
    mainIngredients: ["Carrots", "Labneh", "Sourdough", "Dukkah", "Parsley"],
    pantryMatches: [],
    flavourProfile: ["balanced", "seasonal", "weeknight"],
    isQuick: true,
  },
  {
    slug: "thai-peanut-greens-rice-noodles",
    title: "Thai Peanut Greens Rice Noodles",
    image: "/images/recipes/thai-peanut-greens-rice-noodles.jpg",
    alt: "Thai Peanut Greens Rice Noodles",
    intro: "Rice noodles with greens, herbs and a peanut-lime dressing.",
    body: "Cook the rice noodles until tender, then rinse lightly so they stay separate. Wilt the greens quickly in a hot pan. Mix peanut sauce with lime and warm water until loose and glossy. Toss noodles and greens with the sauce, then finish with coriander.",
    pantryLabel: "Weekly planner meal",
    product: {
      name: "Weekly Produce Box",
      price: 20,
      image: "/weekly-harvest-box.png",
    },
    companionItems: [],
    shopAnchor: "/shop#pantry-additions",
    shopLabel: "Shop pantry range",
    category: "savoury",
    time: "25 mins",
    tags: ["quick-pan", "quick"],

    dietary: ["vegan", "veggie"],
    mealType: "quick-pan",
    difficulty: "easy",
    cookingMinutes: 25,
    protein: ["rice noodles"],
    mainIngredients: [
      "Rice noodles",
      "Greens",
      "Peanut sauce",
      "Lime",
      "Coriander",
    ],
    pantryMatches: [],
    flavourProfile: ["balanced", "seasonal", "weeknight"],
    isQuick: true,
  },
  {
    slug: "baked-feta-butterbeans-greens",
    title: "Baked Feta Butter Beans with Greens",
    image: "/images/recipes/baked-feta-butterbeans-greens.jpg",
    alt: "Baked Feta Butter Beans with Greens",
    intro:
      "Baked feta, butter beans, blistered tomatoes and greens served with toast.",
    body: "Bake feta with tomatoes, olive oil and black pepper until soft and blistered. Add butter beans and return to the oven until bubbling. Fold through greens while everything is still hot. Serve with toast for scooping up the sauce.",
    pantryLabel: "Made with Butter Beans",
    product: {
      name: "Butter Beans",
      price: 3.95,
      image: "/images/cupboard/butter-beans.jpg",
    },
    companionItems: [],
    shopAnchor: "/shop#pantry-additions",
    shopLabel: "Shop pantry range",
    category: "savoury",
    time: "40 mins",
    tags: ["beans", "family-friendly"],

    dietary: ["veggie"],
    mealType: "beans",
    difficulty: "easy",
    cookingMinutes: 40,
    protein: ["butter beans"],
    mainIngredients: ["Feta", "Butter beans", "Greens", "Tomatoes", "Toast"],
    pantryMatches: ["Butter Beans"],
    flavourProfile: ["tomatoey"],
    isQuick: false,
  },
];

export const useItUpIdeas = [
  {
    title: "Herby Grain Bowl",
    text: "Use cooked grains, roast vegetables, leaves, lemon, and any soft herbs. Finish with pesto, tahini, yoghurt, or olive oil.",
  },
  {
    title: "Soup from Almost Anything",
    text: "Soften veg, add stock or water, then blend if you want it smooth. Miso, harissa, tomatoes, or pesto can shift the flavour quickly.",
  },
  {
    title: "End-of-Week Roast Tin",
    text: "Roast what needs using with oil and salt, then finish with herbs, lemon, yoghurt, tahini, or something punchy from a jar.",
  },
  {
    title: "Beans on Something Better Than Toast",
    text: "Warm beans with tomatoes, greens, miso, harissa, or stock, then spoon over toast, potatoes, rice, or couscous.",
  },
  {
    title: "Pasta with the Last Good Things",
    text: "Use pasta as a base for greens, soft tomatoes, roast veg, herbs, nuts, or a spoon of pesto loosened with pasta water.",
  },
  {
    title: "Soft Fruit Bowl",
    text: "If berries, pears, apples, or bananas are softening, spoon them over yoghurt with caramel, chocolate spread, nuts, or toasted oats.",
  },
];

export const prompts = [
  {
    ingredient: "Broccoli",
    idea: "Roast until the edges char, then add gochujang, lemon, yoghurt, or crispy chickpeas.",
  },
  {
    ingredient: "Courgettes",
    idea: "Char in a hot pan and fold through bucatini, pesto, lemon, or basil oil.",
  },
  {
    ingredient: "Tomatoes",
    idea: "Cook down until jammy for pasta, beans, or toast. Finish with basil or black pepper.",
  },
  {
    ingredient: "Mushrooms",
    idea: "Brown properly, then add miso, orzo, rice, greens, or a little stock for depth.",
  },
  {
    ingredient: "Greens",
    idea: "Wilt into beans, orzo, soups, eggs, rice, or pasta right at the end.",
  },
  {
    ingredient: "Beetroot",
    idea: "Roast and pair with farro, walnuts, dill, lemon, yoghurt, or tahini.",
  },
  {
    ingredient: "Peppers",
    idea: "Roast until sweet, then pair with harissa, butter beans, couscous, or tomatoes.",
  },
  {
    ingredient: "Soft fruit",
    idea: "Spoon over yoghurt, cook into compote, or use with caramel, chocolate spread, or toasted nuts.",
  },
];
