export type StaticPlannerRecipe = {
  id: string;
  title: string;
  description: string;
  imageUrl: string;
  mood: "quick" | "balanced" | "comforting";
  eatingStyle: "veg" | "balanced" | "protein";
  focusTags: ("veg-heavy" | "low-waste" | "family-friendly")[];
  ingredients: string[];
  matchedProducts: string[];
  steps: string[];
};

export const staticPlannerRecipes: StaticPlannerRecipe[] = [
  {
    id: "bucatini-courgette-pesto",
    title: "Bucatini with Charred Courgette & Green Pesto",
    description:
      "A quick green pasta with smoky courgette, glossy pesto and a fresh lemon finish.",
    imageUrl: "/images/recipes/bucatini-courgette-pesto.jpg",
    mood: "quick",
    eatingStyle: "veg",
    focusTags: ["family-friendly", "low-waste"],
    ingredients: ["Bucatini", "Courgette", "Green pesto", "Lemon", "Parmesan"],
    matchedProducts: ["Bucatini", "Sorrel & Walnut Pesto"],
    steps: [
      "Cook the bucatini until al dente.",
      "Char sliced courgette in a hot pan with olive oil and salt.",
      "Toss the pasta with pesto, courgette and a splash of pasta water.",
      "Finish with lemon zest, black pepper and parmesan if using.",
    ],
  },
  {
    id: "harissa-butterbeans-peppers-couscous",
    title: "Rose Harissa Butter Beans with Roast Peppers & Giant Couscous",
    description:
      "Soft butter beans, sweet roasted peppers and giant couscous in a warm harissa dressing.",
    imageUrl: "/images/recipes/harissa-butterbeans-peppers-couscous.jpg",
    mood: "comforting",
    eatingStyle: "veg",
    focusTags: ["veg-heavy", "family-friendly"],
    ingredients: [
      "Butter beans",
      "Roast peppers",
      "Giant couscous",
      "Rose harissa",
      "Parsley",
    ],
    matchedProducts: ["Butter Beans", "Giant Couscous", "Rose Harissa"],
    steps: [
      "Cook the giant couscous until tender.",
      "Warm butter beans with olive oil, rose harissa and a splash of water.",
      "Fold through roasted peppers and couscous.",
      "Finish with parsley, lemon and yoghurt if liked.",
    ],
  },
  {
    id: "miso-mushroom-farro-greens",
    title: "Miso Mushrooms with Farro & Greens",
    description:
      "Deeply savoury mushrooms with chewy farro, leafy greens and a miso glaze.",
    imageUrl: "/images/recipes/miso-mushroom-farro.jpg",
    mood: "balanced",
    eatingStyle: "veg",
    focusTags: ["veg-heavy", "low-waste"],
    ingredients: ["Mushrooms", "Farro", "Greens", "White miso", "Garlic"],
    matchedProducts: ["Farro", "White Miso"],
    steps: [
      "Cook the farro until tender.",
      "Fry mushrooms until browned and concentrated.",
      "Stir in garlic, white miso and a splash of water.",
      "Fold through greens and serve over farro.",
    ],
  },
  {
    id: "tomato-chickpea-orzo-herbs",
    title: "Tomato Chickpea Orzo with Herbs",
    description:
      "A one-pan orzo with chickpeas, tomatoes and soft herbs for an easy midweek supper.",
    imageUrl: "/images/recipes/tomato-chickpea-orzo.jpg",
    mood: "quick",
    eatingStyle: "veg",
    focusTags: ["family-friendly", "low-waste"],
    ingredients: ["Orzo", "Chickpeas", "Tomatoes", "Garlic", "Basil"],
    matchedProducts: ["Orzo", "Chickpeas", "Premium Whole Tomatoes"],
    steps: [
      "Soften garlic in olive oil.",
      "Add tomatoes, chickpeas and orzo with enough water to cook gently.",
      "Simmer until the orzo is tender and glossy.",
      "Finish with herbs, black pepper and olive oil.",
    ],
  },
  {
    id: "gochujang-broccoli-rice-bowls",
    title: "Gochujang Broccoli Rice Bowls",
    description:
      "Charred broccoli with sticky gochujang dressing, rice and a cooling crunchy finish.",
    imageUrl: "/images/recipes/gochujang-broccoli-rice-bowl.jpg",
    mood: "quick",
    eatingStyle: "balanced",
    focusTags: ["veg-heavy"],
    ingredients: ["Broccoli", "Rice", "Gochujang", "Cucumber", "Spring onions"],
    matchedProducts: ["Signature Gochujang"],
    steps: [
      "Cook rice until fluffy.",
      "Char broccoli in a hot pan or roasting tray.",
      "Toss broccoli with gochujang, lime and a little sweetness.",
      "Serve with cucumber, spring onions and sesame if using.",
    ],
  },
  {
    id: "cauliflower-lentils-polenta",
    title: "Roast Cauliflower Lentils with Soft Polenta",
    description:
      "A comforting bowl of roasted cauliflower, puy lentils and creamy polenta.",
    imageUrl: "/images/recipes/cauliflower-lentil-polenta.jpg",
    mood: "comforting",
    eatingStyle: "veg",
    focusTags: ["family-friendly", "veg-heavy"],
    ingredients: ["Cauliflower", "Puy lentils", "Polenta", "Thyme", "Garlic"],
    matchedProducts: ["Puy Lentils", "Polenta"],
    steps: [
      "Roast cauliflower with olive oil, salt and thyme.",
      "Warm puy lentils with garlic and a splash of stock or water.",
      "Cook polenta until soft and creamy.",
      "Spoon lentils and cauliflower over the polenta.",
    ],
  },
  {
    id: "aubergine-cannellini-tomatoes",
    title: "Aubergine, Cannellini Beans & Tomatoes",
    description:
      "A soft, tomato-rich pan of aubergine and beans, good with bread, rice or couscous.",
    imageUrl: "/images/recipes/aubergine-cannellini-tomatoes.jpg",
    mood: "comforting",
    eatingStyle: "veg",
    focusTags: ["low-waste", "veg-heavy"],
    ingredients: [
      "Aubergine",
      "Cannellini beans",
      "Tomatoes",
      "Garlic",
      "Parsley",
    ],
    matchedProducts: ["Cannellini Beans", "Premium Whole Tomatoes"],
    steps: [
      "Cook aubergine in olive oil until soft and golden.",
      "Add garlic and tomatoes, then simmer until rich.",
      "Fold through cannellini beans and warm gently.",
      "Finish with parsley and serve with bread, rice or couscous.",
    ],
  },
  {
    id: "beetroot-grain-salad-herbs",
    title: "Beetroot Grain Salad with Herbs",
    description:
      "Earthy beetroot, grains, herbs and a sharp dressing for a useful lunch or light supper.",
    imageUrl: "/images/recipes/beetroot-grain-salad.jpg",
    mood: "balanced",
    eatingStyle: "veg",
    focusTags: ["low-waste"],
    ingredients: ["Beetroot", "Farro", "Parsley", "Lemon", "Walnuts"],
    matchedProducts: ["Farro"],
    steps: [
      "Cook farro until tender, then cool slightly.",
      "Slice cooked beetroot and mix with lemon, oil and salt.",
      "Fold through herbs and walnuts.",
      "Serve as it is or add goat’s cheese if liked.",
    ],
  },
  {
    id: "green-bean-lemon-risotto",
    title: "Green Bean & Lemon Risotto",
    description:
      "A gentle risotto with green beans, lemon and herbs for a calm midweek dinner.",
    imageUrl: "/images/recipes/green-bean-risotto.jpg",
    mood: "balanced",
    eatingStyle: "veg",
    focusTags: ["family-friendly"],
    ingredients: ["Risotto rice", "Green beans", "Lemon", "Parmesan", "Mint"],
    matchedProducts: ["Risotto Rice"],
    steps: [
      "Cook risotto rice gradually with stock or hot water.",
      "Add chopped green beans near the end so they stay bright.",
      "Stir through lemon zest, parmesan and olive oil.",
      "Finish with mint and black pepper.",
    ],
  },
  {
    id: "pepper-potato-herb-frittata",
    title: "Pepper, Potato & Herb Frittata",
    description:
      "A flexible egg-based supper for using up peppers, potatoes and soft herbs.",
    imageUrl: "/images/recipes/pepper-potato-frittata.jpg",
    mood: "quick",
    eatingStyle: "protein",
    focusTags: ["low-waste", "family-friendly"],
    ingredients: ["Eggs", "Peppers", "Potatoes", "Parsley", "Onion"],
    matchedProducts: [],
    steps: [
      "Cook sliced potatoes until tender.",
      "Soften peppers and onion in a pan.",
      "Add beaten eggs and cook gently until almost set.",
      "Finish under the grill and serve with herbs.",
    ],
  },

  {
    id: "salmon-dill-crushed-potato-traybake",
    title: "Salmon, Dill & Crushed Potato Traybake",
    description:
      "A simple traybake with flaky salmon, crushed potatoes, greens and a bright dill finish.",
    imageUrl: "/images/recipes/salmon-dill-crushed-potato-traybake.jpg",
    mood: "balanced",
    eatingStyle: "protein",
    focusTags: ["family-friendly"],
    ingredients: ["Salmon", "Potatoes", "Dill", "Lemon", "Green beans"],
    matchedProducts: [],
    steps: [
      "Boil potatoes until tender, then lightly crush them.",
      "Roast the potatoes with oil and salt until golden.",
      "Add salmon and green beans to the tray.",
      "Finish with lemon, dill and yoghurt if liked.",
    ],
  },
  {
    id: "gochujang-chicken-rice-cucumber",
    title: "Gochujang Chicken Rice Bowls with Cucumber",
    description:
      "Sticky gochujang chicken with rice, cucumber, herbs and a fresh crunchy finish.",
    imageUrl: "/images/recipes/gochujang-chicken-rice-cucumber.jpg",
    mood: "quick",
    eatingStyle: "protein",
    focusTags: ["family-friendly"],
    ingredients: ["Chicken", "Rice", "Gochujang", "Cucumber", "Spring onions"],
    matchedProducts: ["Signature Gochujang"],
    steps: [
      "Cook rice until fluffy.",
      "Pan-fry chicken pieces until golden and cooked through.",
      "Toss chicken with gochujang, lime and a little sweetness.",
      "Serve with cucumber, spring onions and rice.",
    ],
  },
  {
    id: "cashew-broccoli-noodles-lime",
    title: "Cashew Broccoli Noodles with Lime",
    description: "Noodles with charred broccoli, cashew sauce, lime and herbs.",
    imageUrl: "/images/recipes/cashew-broccoli-noodles-lime.jpg",
    mood: "quick",
    eatingStyle: "veg",
    focusTags: ["veg-heavy"],
    ingredients: ["Broccoli", "Rice noodles", "Cashews", "Lime", "Coriander"],
    matchedProducts: [],
    steps: [
      "Cook noodles according to the packet instructions.",
      "Char broccoli in a hot pan.",
      "Blend or stir cashews with lime, soy and warm water to make a sauce.",
      "Toss everything together with herbs and extra lime.",
    ],
  },
  {
    id: "crispy-tofu-peanut-rice-bowls",
    title: "Crispy Tofu Peanut Rice Bowls",
    description:
      "Crispy tofu, vegetables and rice with a creamy peanut-lime sauce.",
    imageUrl: "/images/recipes/crispy-tofu-peanut-rice-bowls.jpg",
    mood: "balanced",
    eatingStyle: "veg",
    focusTags: ["veg-heavy"],
    ingredients: ["Tofu", "Rice", "Peanut sauce", "Cucumber", "Carrots"],
    matchedProducts: [],
    steps: [
      "Press and cube tofu, then fry until crisp.",
      "Cook rice until fluffy.",
      "Make a peanut sauce with lime, soy and warm water.",
      "Serve tofu over rice with vegetables and sauce.",
    ],
  },
  {
    id: "roast-pepper-cashew-cream-casarecce",
    title: "Roast Pepper Cashew Cream Casarecce",
    description:
      "Casarecce folded through a silky roast pepper and cashew cream sauce.",
    imageUrl: "/images/recipes/roast-pepper-cashew-cream-casarecce.jpg",
    mood: "comforting",
    eatingStyle: "veg",
    focusTags: ["family-friendly"],
    ingredients: [
      "Casarecce Pasta",
      "Roast peppers",
      "Cashews",
      "Garlic",
      "Basil",
    ],
    matchedProducts: ["Casarecce Pasta"],
    steps: [
      "Cook the casarecce until al dente.",
      "Blend roast peppers with soaked cashews, garlic and seasoning.",
      "Warm the sauce gently with a splash of pasta water.",
      "Toss through the pasta and finish with basil.",
    ],
  },
  {
    id: "lemon-herb-chicken-giant-couscous",
    title: "Lemon Herb Chicken with Giant Couscous",
    description:
      "Golden chicken with herby giant couscous, vegetables and lemon.",
    imageUrl: "/images/recipes/lemon-herb-chicken-giant-couscous.jpg",
    mood: "balanced",
    eatingStyle: "protein",
    focusTags: ["family-friendly"],
    ingredients: ["Chicken", "Giant couscous", "Lemon", "Parsley", "Courgette"],
    matchedProducts: ["Giant Couscous"],
    steps: [
      "Cook the giant couscous until tender.",
      "Season and pan-fry chicken until cooked through.",
      "Char courgette or other vegetables in the same pan.",
      "Serve with lemon, parsley and olive oil.",
    ],
  },
  {
    id: "salmon-crushed-peas-herby-potatoes",
    title: "Salmon with Crushed Peas & Herby Potatoes",
    description:
      "A fresh salmon supper with crushed peas, soft herbs and potatoes.",
    imageUrl: "/images/recipes/salmon-crushed-peas-herby-potatoes.jpg",
    mood: "balanced",
    eatingStyle: "protein",
    focusTags: ["family-friendly"],
    ingredients: ["Salmon", "Peas", "Potatoes", "Mint", "Lemon"],
    matchedProducts: [],
    steps: [
      "Boil potatoes until tender and toss with herbs.",
      "Cook salmon in a pan or oven until just done.",
      "Crush peas with mint, lemon and olive oil.",
      "Serve salmon with peas and potatoes.",
    ],
  },
  {
    id: "roast-fennel-tomato-burrata-toasts",
    title: "Roast Fennel & Tomato Burrata Toasts",
    description:
      "Sweet roast fennel and tomatoes over toast with creamy burrata.",
    imageUrl: "/images/recipes/roast-fennel-tomato-burrata-toasts.jpg",
    mood: "balanced",
    eatingStyle: "veg",
    focusTags: ["veg-heavy"],
    ingredients: ["Fennel", "Tomatoes", "Burrata", "Sourdough", "Basil"],
    matchedProducts: [],
    steps: [
      "Roast fennel and tomatoes with olive oil and salt.",
      "Toast sourdough until crisp.",
      "Spoon vegetables over the toast.",
      "Tear over burrata and finish with basil.",
    ],
  },
  {
    id: "spinach-ricotta-herb-stuffed-peppers",
    title: "Spinach, Ricotta & Herb Stuffed Peppers",
    description:
      "Sweet peppers filled with spinach, ricotta, herbs and grains.",
    imageUrl: "/images/recipes/spinach-ricotta-herb-stuffed-peppers.jpg",
    mood: "comforting",
    eatingStyle: "veg",
    focusTags: ["family-friendly", "veg-heavy"],
    ingredients: ["Peppers", "Spinach", "Ricotta", "Herbs", "Rice"],
    matchedProducts: [],
    steps: [
      "Halve peppers and roast until beginning to soften.",
      "Mix cooked rice with spinach, ricotta and herbs.",
      "Fill the peppers and bake until golden.",
      "Serve with salad or extra greens.",
    ],
  },
  {
    id: "sticky-soy-chicken-greens-rice",
    title: "Sticky Soy Chicken with Greens & Rice",
    description:
      "Glossy soy chicken with greens, rice and a sharp fresh finish.",
    imageUrl: "/images/recipes/sticky-soy-chicken-greens-rice.jpg",
    mood: "quick",
    eatingStyle: "protein",
    focusTags: ["family-friendly"],
    ingredients: ["Chicken", "Rice", "Greens", "Soy", "Ginger"],
    matchedProducts: [],
    steps: [
      "Cook rice until fluffy.",
      "Pan-fry chicken until golden.",
      "Add soy, ginger and a little sweetness to make a sticky glaze.",
      "Serve with greens and rice.",
    ],
  },

  {
    id: "creamy-tuscan-butterbeans-greens",
    title: "Creamy Tuscan Butter Beans with Greens",
    description:
      "Butter beans in a creamy garlic sauce with greens, herbs and parmesan.",
    imageUrl: "/images/recipes/creamy-tuscan-butterbeans-greens.jpg",
    mood: "comforting",
    eatingStyle: "veg",
    focusTags: ["low-waste", "family-friendly"],
    ingredients: ["Butter beans", "Greens", "Cream", "Garlic", "Parmesan"],
    matchedProducts: ["Butter Beans"],
    steps: [
      "Warm garlic gently in olive oil.",
      "Add butter beans, cream and a splash of water.",
      "Fold through greens until wilted.",
      "Finish with parmesan, herbs and black pepper.",
    ],
  },
  {
    id: "charred-courgette-whipped-feta-orzo",
    title: "Charred Courgette & Whipped Feta Orzo",
    description: "Lemony orzo with charred courgette, herbs and whipped feta.",
    imageUrl: "/images/recipes/charred-courgette-whipped-feta-orzo.jpg",
    mood: "balanced",
    eatingStyle: "veg",
    focusTags: ["family-friendly"],
    ingredients: ["Orzo", "Courgette", "Feta", "Lemon", "Mint"],
    matchedProducts: ["Orzo"],
    steps: [
      "Cook orzo until tender.",
      "Char courgette slices until golden.",
      "Whip or mash feta with lemon and olive oil.",
      "Serve orzo with courgette, herbs and feta.",
    ],
  },
  {
    id: "coconut-lime-greens-crispy-tofu",
    title: "Coconut Lime Greens with Crispy Tofu",
    description: "A coconut-lime greens bowl with crispy tofu and rice.",
    imageUrl: "/images/recipes/coconut-lime-greens-crispy-tofu.jpg",
    mood: "balanced",
    eatingStyle: "veg",
    focusTags: ["veg-heavy"],
    ingredients: ["Tofu", "Greens", "Coconut milk", "Lime", "Rice"],
    matchedProducts: [],
    steps: [
      "Cook rice until fluffy.",
      "Fry tofu until crisp.",
      "Simmer greens briefly with coconut milk, lime and seasoning.",
      "Serve tofu over rice with the coconut greens.",
    ],
  },
  {
    id: "roasted-tomato-burrata-gnocchi",
    title: "Roasted Tomato Burrata Gnocchi",
    description: "Crispy gnocchi with roasted tomatoes, basil oil and burrata.",
    imageUrl: "/images/recipes/roasted-tomato-burrata-gnocchi.jpg",
    mood: "comforting",
    eatingStyle: "veg",
    focusTags: ["family-friendly"],
    ingredients: ["Gnocchi", "Tomatoes", "Burrata", "Basil", "Garlic"],
    matchedProducts: [],
    steps: [
      "Roast tomatoes with garlic, olive oil and salt.",
      "Pan-fry or bake gnocchi until golden.",
      "Toss gnocchi with the roasted tomatoes.",
      "Finish with burrata and basil.",
    ],
  },
  {
    id: "hot-honey-halloumi-herby-couscous",
    title: "Hot Honey Halloumi with Herby Couscous",
    description:
      "Golden halloumi with lemony couscous, herbs and a chilli honey finish.",
    imageUrl: "/images/recipes/hot-honey-halloumi-couscous.jpg",
    mood: "quick",
    eatingStyle: "veg",
    focusTags: ["family-friendly"],
    ingredients: [
      "Halloumi",
      "Giant couscous",
      "Cucumber",
      "Mint",
      "Hot honey",
    ],
    matchedProducts: ["Giant Couscous"],
    steps: [
      "Cook giant couscous until tender.",
      "Pan-fry halloumi until golden.",
      "Toss couscous with herbs, cucumber and lemon.",
      "Drizzle halloumi with hot honey and serve.",
    ],
  },
  {
    id: "smoky-sweet-potato-black-bean-bowls",
    title: "Smoky Sweet Potato Black Bean Bowls",
    description: "Roasted sweet potato, black beans, rice and avocado yoghurt.",
    imageUrl: "/images/recipes/smoky-sweet-potato-black-bean-bowls.jpg",
    mood: "balanced",
    eatingStyle: "veg",
    focusTags: ["veg-heavy", "family-friendly"],
    ingredients: [
      "Sweet potato",
      "Black beans",
      "Rice",
      "Avocado",
      "Coriander",
    ],
    matchedProducts: [],
    steps: [
      "Roast sweet potato with smoky spices.",
      "Warm black beans with lime and seasoning.",
      "Cook rice until fluffy.",
      "Serve with avocado yoghurt and herbs.",
    ],
  },
  {
    id: "chicken-leek-mustard-cream-casarecce",
    title: "Chicken, Leek & Mustard Cream Casarecce",
    description:
      "A comforting casarecce with chicken, soft leeks and mustard cream.",
    imageUrl: "/images/recipes/chicken-leek-mustard-cream-casarecce.jpg",
    mood: "comforting",
    eatingStyle: "protein",
    focusTags: ["family-friendly"],
    ingredients: ["Casarecce Pasta", "Chicken", "Leeks", "Mustard", "Cream"],
    matchedProducts: ["Casarecce Pasta"],
    steps: [
      "Cook the casarecce until al dente.",
      "Soften leeks in butter or oil.",
      "Add cooked chicken, mustard and cream.",
      "Toss with pasta and finish with black pepper.",
    ],
  },
  {
    id: "roasted-carrot-labneh-toasts-dukkah",
    title: "Roasted Carrot Labneh Toasts with Dukkah",
    description:
      "Roasted carrots over thick labneh on toast with herbs and dukkah.",
    imageUrl: "/images/recipes/roasted-carrot-labneh-toasts.jpg",
    mood: "balanced",
    eatingStyle: "veg",
    focusTags: ["veg-heavy"],
    ingredients: ["Carrots", "Labneh", "Sourdough", "Dukkah", "Parsley"],
    matchedProducts: [],
    steps: [
      "Roast carrots with olive oil and salt.",
      "Toast sourdough until crisp.",
      "Spread with labneh.",
      "Top with carrots, herbs and dukkah.",
    ],
  },
  {
    id: "thai-peanut-greens-rice-noodles",
    title: "Thai Peanut Greens Rice Noodles",
    description: "Rice noodles with greens, herbs and a peanut-lime dressing.",
    imageUrl: "/images/recipes/thai-peanut-greens-rice-noodles.jpg",
    mood: "quick",
    eatingStyle: "balanced",
    focusTags: ["low-waste"],
    ingredients: [
      "Rice noodles",
      "Greens",
      "Peanut sauce",
      "Lime",
      "Coriander",
    ],
    matchedProducts: [],
    steps: [
      "Cook rice noodles until tender.",
      "Wilt greens quickly in a hot pan.",
      "Mix peanut sauce with lime and warm water.",
      "Toss noodles, greens and sauce together.",
    ],
  },
  {
    id: "baked-feta-butterbeans-greens",
    title: "Baked Feta Butter Beans with Greens",
    description:
      "Baked feta, butter beans, blistered tomatoes and greens served with toast.",
    imageUrl: "/images/recipes/baked-feta-butterbeans-greens.jpg",
    mood: "comforting",
    eatingStyle: "veg",
    focusTags: ["family-friendly", "low-waste"],
    ingredients: ["Feta", "Butter beans", "Greens", "Tomatoes", "Toast"],
    matchedProducts: ["Butter Beans"],
    steps: [
      "Bake feta with tomatoes, olive oil and seasoning.",
      "Add butter beans and return to the oven until bubbling.",
      "Fold through greens until wilted.",
      "Serve with toast or bread.",
    ],
  },

  {
    id: "coconut-tomato-chickpea-curry-rice",
    title: "Coconut Tomato Chickpea Curry with Rice",
    description: "A gentle curry with chickpeas, tomatoes, coconut and greens.",
    imageUrl: "/images/recipes/coconut-tomato-chickpea-curry-rice.jpg",
    mood: "comforting",
    eatingStyle: "veg",
    focusTags: ["family-friendly", "veg-heavy"],
    ingredients: ["Chickpeas", "Tomatoes", "Coconut milk", "Greens", "Rice"],
    matchedProducts: ["Chickpeas", "Premium Whole Tomatoes"],
    steps: [
      "Cook rice until fluffy.",
      "Simmer tomatoes, chickpeas and coconut milk together.",
      "Add greens until wilted.",
      "Serve with herbs and lime if liked.",
    ],
  },
  {
    id: "white-bean-parmesan-broth-greens-toasts",
    title: "White Bean Parmesan Broth with Greens & Toasts",
    description:
      "A brothy white bean bowl with greens, parmesan and crisp toasts.",
    imageUrl: "/images/recipes/white-bean-parmesan-broth-greens.jpg",
    mood: "comforting",
    eatingStyle: "veg",
    focusTags: ["low-waste"],
    ingredients: ["Cannellini beans", "Greens", "Parmesan", "Garlic", "Toast"],
    matchedProducts: ["Cannellini Beans"],
    steps: [
      "Warm garlic in olive oil.",
      "Add beans and stock or water, then simmer gently.",
      "Stir through greens.",
      "Finish with parmesan and serve with toasts.",
    ],
  },
  {
    id: "harissa-chickpea-flatbreads-herbs",
    title: "Harissa Chickpea Flatbreads with Herbs",
    description:
      "Warm flatbreads with harissa chickpeas, yoghurt, herbs and cucumber.",
    imageUrl: "/images/recipes/harissa-chickpea-flatbreads-herbs.jpg",
    mood: "quick",
    eatingStyle: "veg",
    focusTags: ["family-friendly"],
    ingredients: [
      "Chickpeas",
      "Rose harissa",
      "Flatbreads",
      "Yoghurt",
      "Cucumber",
    ],
    matchedProducts: ["Chickpeas", "Rose Harissa"],
    steps: [
      "Warm chickpeas with rose harissa and olive oil.",
      "Toast or warm flatbreads.",
      "Spoon over yoghurt, cucumber and chickpeas.",
      "Finish with herbs and lemon.",
    ],
  },
  {
    id: "green-lentil-coconut-curry-bowls",
    title: "Green Lentil Coconut Curry Bowls",
    description:
      "Green lentils simmered with coconut, spices and seasonal greens.",
    imageUrl: "/images/recipes/green-lentil-coconut-curry-bowls.jpg",
    mood: "comforting",
    eatingStyle: "veg",
    focusTags: ["veg-heavy", "low-waste"],
    ingredients: [
      "Green lentils",
      "Coconut milk",
      "Greens",
      "Rice",
      "Coriander",
    ],
    matchedProducts: [],
    steps: [
      "Simmer lentils until tender.",
      "Add coconut milk and gentle spices.",
      "Fold through greens.",
      "Serve with rice and coriander.",
    ],
  },
  {
    id: "lemon-kale-bucatini-parmesan",
    title: "Lemon Kale Bucatini with Parmesan",
    description:
      "A simple bright bucatini with kale, lemon, parmesan and black pepper.",
    imageUrl: "/images/recipes/lemon-kale-bucatini-parmesan.jpg",
    mood: "quick",
    eatingStyle: "veg",
    focusTags: ["low-waste"],
    ingredients: ["Bucatini", "Kale", "Lemon", "Parmesan", "Garlic"],
    matchedProducts: ["Bucatini"],
    steps: [
      "Cook bucatini until al dente.",
      "Soften garlic and kale in olive oil.",
      "Toss pasta with kale, lemon and pasta water.",
      "Finish with parmesan and black pepper.",
    ],
  },
  {
    id: "walnut-herb-farro-roast-vegetables",
    title: "Walnut Herb Farro with Roast Vegetables",
    description:
      "A robust grain bowl with roasted vegetables, walnuts and herbs.",
    imageUrl: "/images/recipes/walnut-herb-farro-roast-vegetables.jpg",
    mood: "balanced",
    eatingStyle: "veg",
    focusTags: ["veg-heavy", "low-waste"],
    ingredients: ["Farro", "Roast vegetables", "Walnuts", "Parsley", "Lemon"],
    matchedProducts: ["Farro"],
    steps: [
      "Roast mixed vegetables until golden.",
      "Cook farro until chewy and tender.",
      "Toss with herbs, lemon and walnuts.",
      "Serve warm or room temperature.",
    ],
  },
  {
    id: "charred-greens-tahini-yoghurt-crispy-chickpeas",
    title: "Charred Greens with Tahini Yoghurt & Crispy Chickpeas",
    description:
      "Smoky greens with creamy tahini yoghurt and crunchy chickpeas.",
    imageUrl: "/images/recipes/charred-greens-tahini-yoghurt-chickpeas.jpg",
    mood: "balanced",
    eatingStyle: "veg",
    focusTags: ["veg-heavy"],
    ingredients: ["Greens", "Chickpeas", "Tahini", "Yoghurt", "Lemon"],
    matchedProducts: ["Chickpeas"],
    steps: [
      "Roast chickpeas until crisp.",
      "Char greens in a hot pan.",
      "Mix tahini, yoghurt, lemon and salt.",
      "Serve greens with sauce and chickpeas.",
    ],
  },
  {
    id: "roasted-squash-puy-lentils-herbs",
    title: "Roasted Squash & Puy Lentils with Herbs",
    description:
      "Sweet squash with earthy lentils, herbs and a sharp dressing.",
    imageUrl: "/images/recipes/roasted-squash-puy-lentils-herbs.jpg",
    mood: "balanced",
    eatingStyle: "veg",
    focusTags: ["veg-heavy", "low-waste"],
    ingredients: ["Squash", "Puy lentils", "Parsley", "Lemon", "Yoghurt"],
    matchedProducts: ["Puy Lentils"],
    steps: [
      "Roast squash until caramelised.",
      "Warm puy lentils with olive oil and seasoning.",
      "Toss with herbs and lemon.",
      "Serve with yoghurt if liked.",
    ],
  },
  {
    id: "citrus-herb-halloumi-couscous-salad",
    title: "Citrus Herb Halloumi Salad with Couscous",
    description:
      "Golden halloumi with couscous, citrus, herbs and crisp vegetables.",
    imageUrl: "/images/recipes/citrus-herb-halloumi-couscous-salad.jpg",
    mood: "quick",
    eatingStyle: "veg",
    focusTags: ["family-friendly"],
    ingredients: ["Halloumi", "Giant couscous", "Orange", "Cucumber", "Mint"],
    matchedProducts: ["Giant Couscous"],
    steps: [
      "Cook giant couscous until tender.",
      "Pan-fry halloumi until golden.",
      "Toss couscous with citrus, cucumber and herbs.",
      "Top with halloumi and extra citrus dressing.",
    ],
  },
  {
    id: "creamy-tofu-korma-greens-rice",
    title: "Creamy Tofu Korma with Greens & Rice",
    description: "A mild creamy tofu korma with greens and fluffy rice.",
    imageUrl: "/images/recipes/creamy-tofu-korma-greens-rice.jpg",
    mood: "comforting",
    eatingStyle: "veg",
    focusTags: ["family-friendly"],
    ingredients: ["Tofu", "Rice", "Greens", "Korma sauce", "Coriander"],
    matchedProducts: [],
    steps: [
      "Cook rice until fluffy.",
      "Fry tofu until lightly golden.",
      "Warm korma sauce with greens until tender.",
      "Serve tofu and sauce over rice with coriander.",
    ],
  },
];
